const NEW_MESSAGE='NEW_MESSAGE';
const POST_MESSAGE='POST_MESSAGE';
const UPDATE_MESSAGE='UPDATE_MESSAGE'
const POST_PRODUCT='POST_PRODUCT'
const NEW_PRODUCT='NEW_PRODUCT';

module.exports={
    NEW_MESSAGE,
    POST_MESSAGE,
    UPDATE_MESSAGE,
    POST_PRODUCT,
    NEW_PRODUCT
}